Adds archived plugins to the site
ManimCommunity/plugins-site pull request #15
Opened 2021-09-11 15:28 UTC by GameDungeon

Adds a manually controlled plugin list to display as archived.
![image](https://user-images.githubusercontent.com/60719255/132952984-c3dc5b03-d3ef-4f64-bbc3-ae50b1720abb.png)

Somone should make this better in the future, but this implementation works for now.

2021-09-13 11:26 UTC, naveen521kk requested changes
Can you remove the changes from `package-lock.json`?

2021-09-13 11:29 UTC, naveen521kk commented on src/main.css
>  }
Add a new line here.
```suggestion
}

```

2021-09-14 00:57 UTC, GameDungeon commented
Fixed

2021-09-14 04:11 UTC, naveen521kk approved these changes
Lgtm

2021-09-14 04:12 UTC, merged